# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-25 04:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locationmovies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=60)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterModelManagers(
            name='movies',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='movies',
            name='release_year',
            field=models.CharField(max_length=4),
        ),
        migrations.AddField(
            model_name='users',
            name='favorite_id',
            field=models.ManyToManyField(to='locationmovies.Favorites'),
        ),
    ]
