# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-28 05:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locationmovies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorites',
            name='movie_id',
        ),
        migrations.RemoveField(
            model_name='users',
            name='favorites_id',
        ),
        migrations.AddField(
            model_name='movies',
            name='favorited_by',
            field=models.ManyToManyField(to='locationmovies.Users'),
        ),
        migrations.DeleteModel(
            name='Favorites',
        ),
    ]
