# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-28 06:04
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('locationmovies', '0002_auto_20161027_2229'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='movies',
            managers=[
                ('MoviesManager', django.db.models.manager.Manager()),
            ],
        ),
    ]
